// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wEZN3Y2o4rzJQDQC8iKijz
// Component: AguaQzx-_iyPk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: j9EbzKQ8QuL/component
import CopyableLink from "../../CopyableLink"; // plasmic-import: d5eqV2NjQkqRh/component
import { useScreenVariants as useScreenVariantsc5WEJtX6XthEv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: c5wEJtX6xthEV/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: wEZN3Y2o4rzJQDQC8iKijz/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: AguaQzx-_iyPk/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: gBTy-MulV41OU/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: PpI-KN0hatVXc/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: JJ9WIdqjXR4wV/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsc5WEJtX6XthEv()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__emE8P)}>
            <div className={classNames(projectcss.all, sty.freeBox___3CRke)} />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bVj7B)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__xG3ID)}>
                <div className={classNames(projectcss.all, sty.freeBox__ibiJp)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pScR
                    )}
                  >
                    {"Your Name"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___72Mcl
                    )}
                  >
                    {"Your Slug Line Here\nCan Be Multiple Lines"}
                  </div>

                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    color={"blue"}
                    shape={"rounded"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__byGLz
                      )}
                    >
                      {"Download Resume"}
                    </div>
                  </Button>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__yH1Hh)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mfvpV
                  )}
                >
                  {" "}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__zgtyi)}>
                  <CopyableLink
                    data-plasmic-name={"copyableLink"}
                    data-plasmic-override={overrides.copyableLink}
                    className={classNames("__wab_instance", sty.copyableLink)}
                  >
                    {"youremail@gmail.com"}
                  </CopyableLink>
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vXNp)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__odNah)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vato3
                      )}
                      href={"https://www.twitter.com"}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__j8Q5M)}
                        role={"img"}
                      />
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vg2E3
                      )}
                      href={"https://www.dribbble.com"}
                    >
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg___52Nrc)}
                        role={"img"}
                      />
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__gkoxU
                      )}
                      href={"https://www.github.com"}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__r7DsD)}
                        role={"img"}
                      />
                    </a>
                  </p.Stack>
                </p.Stack>
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__otjqh)} />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "button", "copyableLink"],
  button: ["button"],
  copyableLink: ["copyableLink"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    copyableLink: makeNodeComponent("copyableLink"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
