// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wEZN3Y2o4rzJQDQC8iKijz
// Component: Fd6vx1Rydf
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: wEZN3Y2o4rzJQDQC8iKijz/projectcss
import sty from "./PlasmicDownloadResumeButton.module.css"; // plasmic-import: Fd6vx1Rydf/css

export const PlasmicDownloadResumeButton__VariantProps = new Array();

export const PlasmicDownloadResumeButton__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicDownloadResumeButton__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDownloadResumeButton__ArgProps,
          internalVariantPropNames: PlasmicDownloadResumeButton__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDownloadResumeButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDownloadResumeButton";
  } else {
    func.displayName = `PlasmicDownloadResumeButton.${nodeName}`;
  }
  return func;
}

export const PlasmicDownloadResumeButton = Object.assign(
  // Top-level PlasmicDownloadResumeButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicDownloadResumeButton
    internalVariantProps: PlasmicDownloadResumeButton__VariantProps,
    internalArgProps: PlasmicDownloadResumeButton__ArgProps
  }
);

export default PlasmicDownloadResumeButton;
/* prettier-ignore-end */
